#!/usr/bin/env bash
# keychain_bootstrap.sh — Generate .env.secrets from macOS Keychain.
#
# Reads all Noa secrets from the macOS Keychain and writes them to
# .env.secrets in the project root. This file is consumed by
# docker-compose via env_file directive.
#
# Usage:
#   ./tools/keychain_bootstrap.sh [output-path]
#
# Default output: .env.secrets (project root)
# SPEC.md §11.1, §11.2

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="${1:-$PROJECT_ROOT/.env.secrets}"

# Secret key names in keychain → env var names
# Account names in Keychain → env var names
# Keys are stored under service "noa" with ENV_VAR style account names
declare -A SECRETS=(
    ["SECRET_KEY"]="SECRET_KEY"
    ["POSTGRES_PASSWORD"]="POSTGRES_PASSWORD"
    ["JWT_SECRET"]="JWT_SECRET"
    ["BACKUP_PASSPHRASE"]="BACKUP_PASSPHRASE"
    ["ANTHROPIC_API_KEY"]="ANTHROPIC_API_KEY"
    ["OPENAI_API_KEY"]="OPENAI_API_KEY"
    ["GOOGLE_AI_API_KEY"]="GOOGLE_AI_API_KEY"
    ["GOOGLE_CLIENT_ID"]="GOOGLE_CLIENT_ID"
    ["GOOGLE_CLIENT_SECRET"]="GOOGLE_CLIENT_SECRET"
    ["NOTION_TOKEN"]="NOTION_TOKEN"
    ["TAVILY_API_KEY"]="TAVILY_API_KEY"
)

echo "# Auto-generated by keychain_bootstrap.sh — DO NOT EDIT" > "$OUTPUT"
echo "# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$OUTPUT"
echo "" >> "$OUTPUT"

FOUND=0
MISSING=0

for keychain_name in "${!SECRETS[@]}"; do
    env_var="${SECRETS[$keychain_name]}"
    value=$("$SCRIPT_DIR/keychain_store.sh" get "$keychain_name" 2>/dev/null) || true
    if [[ -n "$value" ]]; then
        echo "${env_var}=${value}" >> "$OUTPUT"
        FOUND=$((FOUND + 1))
    else
        echo "# ${env_var}= (not found in keychain)" >> "$OUTPUT"
        MISSING=$((MISSING + 1))
    fi
done

chmod 600 "$OUTPUT"

echo "Written to: $OUTPUT"
echo "Found: $FOUND secrets, Missing: $MISSING secrets"

if [[ $MISSING -gt 0 ]]; then
    echo ""
    echo "To add missing secrets, run:"
    echo "  ./tools/keychain_store.sh set <key-name> <value>"
    echo ""
    echo "Available key names:"
    for keychain_name in "${!SECRETS[@]}"; do
        echo "  $keychain_name → ${SECRETS[$keychain_name]}"
    done
fi
